services:
  microreservation_api:
    image: ${DOCKER_REGISTRY-}reservationmicroservice:v1
    deploy:
      mode: replicated
      replicas: 1
    build:
      context: ./
      dockerfile: MicroReservation.API/Dockerfile
    ports:
      - "5068:5068"
      - "7041:7041"

    env_file:
      - common.env
  microlaundryapi:
    image: ${DOCKER_REGISTRY-}laundrymicroservice:v1
    deploy:
      mode: replicated
      replicas: 3
    build:
      context: ./
      dockerfile: MicroLaundry.API/Dockerfile
    env_file:
      - common.env
  microhotelservice_api:
    image: ${DOCKER_REGISTRY-}hotelservicemicroservice:v1
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: ./
      dockerfile: MicroHotelService.API/Dockerfile
    env_file:
      - common.env
  microcuisine_api:
    image: ${DOCKER_REGISTRY-}cuisinemicroservice:v1
    deploy:
      mode: replicated
      replicas: 2
    build:
      context: ./
      dockerfile: MicroCuisine.API/Dockerfile
    env_file:
      - common.env
  microcleanservice_api:
    image: ${DOCKER_REGISTRY-}cleansrvicemicroservice:v1
    deploy:
      mode: replicated
      replicas: 3
    build:
      context: ./
      dockerfile: MicroCleanService.API/Dockerfile
    env_file:
      - common.env